apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.images.grafana.tag}}
  name: grafana-config
  namespace: {{ .Values.namespace }}
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = browser
    [server]
    serve_from_sub_path = true
type: Opaque
