apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: {{ .Values.images.prometheus_operator.tag}}
  name: prometheus-operator
  namespace: {{ .Values.namespace }}
