---
# Source: monitoring/templates/serviceandservicemonitor/etcd-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-etcd
  namespace: kube-system
  labels:
    app: kube-etcd
    release: k8s
spec:
  clusterIP: None 
  ports:
    - name: https
      protocol: TCP
      port: 2379
      targetPort: 2379
  selector:
    app: kube-etcd
  clusterIPs:
    - None
