---
# Source: monitoring/templates/serviceandservicemonitor/etcd-endpoint.yaml
apiVersion: v1
kind: Endpoints
metadata: 
  name: kube-etcd
  namespace: kube-system
subsets:
  - addresses:
      - ip: 10.255.63.85
    ports:
      - name: https
        port: 2379
        protocol: TCP
