---
# roles/common/tasks/configure_registry.yml

- name: Ensure registry configuration directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Deploy RKE2 registries.yaml
  template:
    src: registries.yaml.j2
    dest: /etc/rancher/rke2/registries.yaml
    mode: '0644'
