apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-master
  namespace: elastic
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: "key1"
        operator: "Equal"
        value: "value1"
        effect: NoSchedule
      nodeSelector:
        node: admin
      containers:
      - name: fluentd
        imagePullPolicy: "Always"
        image: registry.kcntt.net/fluent/fluentd-kubernetes-daemonset:v1.16.3-debian-elasticsearch7-amd64-2.1
        ports:
          - name: liveness
            containerPort: 20050
            protocol: TCP
          - name: readiness
            containerPort: 20040
            protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        envFrom:
          - configMapRef:
              name: fluentd-audit-cm
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        livenessProbe:
          httpGet:
            path: /api/plugins
            port: liveness
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: readiness
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 10
          periodSeconds: 12
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config-ms
      - name: varlog
        hostPath:
          path: /var/log/kubernetes/audit/
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
