---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - open-iscsi
      - nfs-common
      - bash
      - cryptsetup
      - dmsetup
    state: present

- name: Enable and start iscsid
  ansible.builtin.service:
    name: iscsid
    state: started
    enabled: true
