apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: devops-tools
  labels:
    app: curl-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: [ "sleep", "infinity" ]
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  labels:
    app: curl-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: [ "sleep", "infinity" ]
  restartPolicy: Always