---
# Source: monitoring/templates/manifests/alertmanager-alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.26.0
    app.owner: nguyenchitao
    app.developer: nguyenchitao
  name: main
  namespace: monitoring
spec:
  containers:
    - env: []
      image: quay.io/prometheus/alertmanager:v0.26.0
      name: alertmanager
      volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.26.0
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  secrets: []
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: 0.26.0
  volumes:
    - hostPath:
        path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
      name: timezone
