---
# Source: monitoring/templates/manifests/grafana-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 10.2.0
    app.owner: nguyenchitao
    app.developer: nguyenchitao
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      annotations:
        checksum/grafana-config: fa44ea85feb223f835489871f51821d7
        checksum/grafana-dashboardproviders: 99dbbbc5af9bc4462192853e24ebd262
        checksum/grafana-datasources: 70205f42d36b3f2a0ec9786f8bfa06e8
      labels:
        app.kubernetes.io/component: grafana
        app.kubernetes.io/name: grafana
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 10.2.0

    spec:
      automountServiceAccountToken: false
      containers:
      - env: []
        image:  grafana/grafana:10.2.0
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false
        - mountPath: /tmp
          name: tmp-plugins
          readOnly: false
        - mountPath: /etc/localtime
          name: timezone

        - name: grafana-proxy
          mountPath: /grafana-dashboard-definitions/0/grafana-proxy
        - name: grafana-etcd
          mountPath: /grafana-dashboard-definitions/0/grafana-etcd
        - name: grafana-kubelet
          mountPath: /grafana-dashboard-definitions/0/grafana-kubelet
        - name: grafana-coredns
          mountPath: /grafana-dashboard-definitions/0/grafana-coredns
        - name: grafana-kubernetes-apiserver
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-apiserver
        - name: grafana-kubernetes-computeresources-cluster
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-cluster
        - name: grafana-kubernetes-computeresources-namespace-pods
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-namespace-pods
        - name: grafana-kubernetes-computeresources-namespace-workloads
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-namespace-workloads
        - name: grafana-kubernetes-computeresources-node-pods
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-node-pods
        - name: grafana-kubernetes-computeresources-pod
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-pod
        - name: grafana-kubernetes-computeresources-workload
          mountPath: /grafana-dashboard-definitions/0/grafana-kubernetes-computeresources-workload
        - name: grafana-networking-cluster
          mountPath: /grafana-dashboard-definitions/0/grafana-networking-cluster
        - name: grafana-networking-namespace-workload
          mountPath: /grafana-dashboard-definitions/0/grafana-networking-namespace-workload
        - name: grafana-networking-pod
          mountPath: /grafana-dashboard-definitions/0/grafana-networking-pod
        - name: grafana-networking-workload
          mountPath: /grafana-dashboard-definitions/0/grafana-networking-workload
        - name: grafana-persistent-volumes
          mountPath: /grafana-dashboard-definitions/0/grafana-persistent-volumes 
        - name: grafana-scheduler
          mountPath: /grafana-dashboard-definitions/0/grafana-scheduler
        - name: grafana-certificates-expiration
          mountPath: /grafana-dashboard-definitions/0/grafana-certificates-expiration
        - name: grafana-control-management
          mountPath: /grafana-dashboard-definitions/0/grafana-control-management
        - name: grafana-node-exporter
          mountPath: /grafana-dashboard-definitions/0/grafana-node-exporter
      nodeSelector:
        
        app.kubernetes.io/name: linux
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards
      - emptyDir:
          medium: Memory
        name: tmp-plugins
      - name: grafana-config
        secret:
          secretName: grafana-config
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: ""
        name: timezone
        
      - configMap:
          defaultMode: 420
          name: grafana-proxy
        name: grafana-proxy
        
      - configMap:
          defaultMode: 420
          name: grafana-etcd
        name: grafana-etcd

      - configMap:
          defaultMode: 420
          name: grafana-kubelet
        name: grafana-kubelet

      - configMap:
          defaultMode: 420
          name: grafana-coredns
        name: grafana-coredns

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-apiserver
        name: grafana-kubernetes-apiserver

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-cluster
        name: grafana-kubernetes-computeresources-cluster

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-namespace-pods
        name: grafana-kubernetes-computeresources-namespace-pods

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-namespace-workloads
        name: grafana-kubernetes-computeresources-namespace-workloads

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-node-pods
        name: grafana-kubernetes-computeresources-node-pods

      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-pod
        name: grafana-kubernetes-computeresources-pod
      - configMap:
          defaultMode: 420
          name: grafana-kubernetes-computeresources-workload
        name: grafana-kubernetes-computeresources-workload
      - configMap:
          defaultMode: 420
          name: grafana-networking-cluster
        name: grafana-networking-cluster
      - configMap:
          defaultMode: 420
          name: grafana-networking-namespace-workload
        name: grafana-networking-namespace-workload
      - configMap:
          defaultMode: 420
          name: grafana-networking-pod
        name: grafana-networking-pod
      - configMap:
          defaultMode: 420
          name: grafana-networking-workload
        name: grafana-networking-workload
      - configMap:
          defaultMode: 420
          name: grafana-persistent-volumes
        name: grafana-persistent-volumes
      - configMap:
          defaultMode: 420
          name: grafana-scheduler
        name: grafana-scheduler
      - configMap:
          defaultMode: 420
          name: grafana-certificates-expiration
        name: grafana-certificates-expiration
      - configMap:
          defaultMode: 420
          name: grafana-control-management
        name: grafana-control-management
      - configMap:
          defaultMode: 420
          name: grafana-node-exporter
        name: grafana-node-exporter
