name: 'E2E Test Report'

on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        with:
          artifact: /e2e-test-reports-(.*)/
          name: JEST Tests $1               # Name of the check run which will be created
          path: 'report*.xml'               # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
          fail-on-empty: 'true'
