name: Adds all issues

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
      issues: write
    steps:
      - uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458 # v1.0.1
        with:
          project-url: https://github.com/orgs/kubernetes/projects/104
          github-token: ${{ secrets.PROJECT_WRITER }}
