---
# Source: thanos/templates/ruler/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-thanos-ruler-alertmanagers-config
  namespace: thanos
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 0.39.2
    helm.sh/chart: thanos-17.3.1
    app.kubernetes.io/component: ruler
stringData:
  alertmanager.yaml: |-
    global:
      smtp_from: nguyenchitao1582000@gmail.com
      smtp_auth_identity: nguyenchitao1582000@gmail.com
      smtp_require_tls: false
      smtp_auth_password: Nguyentao15820@
      smtp_auth_username: nguyenchitao1582000@gmail.com
      smtp_hello: smtp.nguyenchitao.com.vn
      smtp_smarthost: smtp.nguyenchitao.com.vn:465

    templates:
      - "/etc/alertmanager/config/*.tmpl"
      - /conf/alertmanagers/alertmanagers_config.yml
    route:
      group_by: ["alertname" ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: node-warning

      routes:
        - matchers:
            - job="kube-state-metrics" 
          receiver: kube-warning
          continue: true
          routes:
            - matchers:
                - severity="warning" 
              receiver: kube-warning
            #- matchers:
            #  - severity="info"
            #  receiver: kube-info 

        - matchers:
            - job="node-exporter"
          receiver: node-warning
          continue: true
          routes:
            - matchers:
                - severity="warning" 
              receiver: node-warning
          #  - matchers:
          #      - severity="info"
          #    receiver: node-info 
    inhibit_rules:
      #    - source_matchers: [severity="warning"]
      #    target_matchers: [severity="info"]
      #    equal: ["severity"]

      - source_matchers: [severity="warning"]
        target_matchers: [severity="info"]
        equal: ["severity"]

    receivers:
      - name: "node-warning"
        email_configs:
          - to: "nguyenchitao1582000@gmail.com"
            send_resolved: true
            headers:
              Subject: "[Hệ thống ...] Có cảnh báo mới"
              From: ""
            html: '{{ template "email.nguyenchitao-node.html" . }}'

      - name: "kube-warning"
        email_configs:
          - to: "nguyenchitao1582000@gmail.com"
            send_resolved: true
            headers:
              Subject: "[Hệ thống ...] Có cảnh báo mới"
              From: ""
            html: '{{ template "email.nguyenchitao-kube.html" . }}'

  email-kube.tmpl: |-
    {{ define "email.nguyenchitao-kube.subject" }}Alert on {{ range.Alerts.Firing
    }}{{ .Labels.instance }} {{ end }}{{ end }}
    {{ define "email.nguyenchitao-kube.html" }}
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <title>[AlertManager] Cảnh báo: {{ .GroupLabels.alertname }}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            line-height: 1.6;
          }

          h1,
          h2,
          h3 {
            margin: 0;
            padding: 0;
          }

          .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f7f7f7;
            border: 1px solid #e5e5e5;
          }

          .header {
            background-color: #fdfdff00;
            color: #000000;
            padding: 20px;
            text-align: center;
          }

          .logo {
            width: 200px;
            margin: 0 auto;
          }

          .alert {
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
          }
          .warning {
            background-color: #ffc107;
            color: #212529;
          }

          .footer {
            margin-top: 20px;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Hệ thống ... nội bộ có cảnh báo mới về Kubernetes</h1>
            <h2><strong>Số lượng cảnh báo: </strong>{{ .Alerts | len }}</h2>
          </div>
          <h3>Thông tin chi tiết cảnh báo:</h3>
          {{ range.Alerts }}
          <div class="alert {{ .Labels.severity }}">
            <h2>{{ .Labels.alertname }}</h2>
            <p><strong>Mức độ: </strong>{{ .Labels.severity }}</p>
            <p><strong>Namespace: </strong>{{ .Labels.namespace }}</p>
            <p><strong>Giá trị hiện tại: </strong>{{ .Annotations.value }}</p>
            <p><strong>Thông điệp: </strong>{{ .Annotations.summary }}</p>
            <p>
              <strong>Thời gian bắt đầu: </strong
              >{{ .StartsAt.Local.Format "01/02/2006 15:04:05 " }}
            </p>
            <p><strong> Mô tả chi tiết: </strong>{{ .Annotations.description }}</p>
          </div>
          {{ end }}

          <p>
            Chúng tôi đang theo dõi tình trạng này và sẽ tiếp tục giám sát các sự
            kiện liên quan. Vui lòng kiểm tra và xử lý cảnh báo này càng sớm càng
            tốt.
          </p>

          <div class="footer">
            <p>Trân trọng</p>
          </div>
        </div>
      </body>
    </html>
    {{ end }}

  email-node.tmpl: |-
    {{ define "email.nguyenchitao-node.subject" }}Alert on {{ range.Alerts.Firing
    }}{{ .Labels.instance }} {{ end }}{{ end }}
    {{ define "email.nguyenchitao-node.html" }}
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <title>[AlertManager] Cảnh báo: {{ .GroupLabels.alertname }}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            line-height: 1.6;
          }

          h1,
          h2,
          h3 {
            margin: 0;
            padding: 0;
          }

          .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f7f7f7;
            border: 1px solid #e5e5e5;
          }

          .header {
            background-color: #fdfdff00;
            color: #000000;
            padding: 20px;
            text-align: center;
          }

          .logo {
            width: 200px;
            margin: 0 auto;
          }

          .alert {
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
          }


          .warning {
            background-color: #ffc107;
            color: #212529;
          }

          .footer {
            margin-top: 20px;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Hệ thống ... nội bộ có cảnh báo mới về Node</h1>
            <h2><strong>Số lượng cảnh báo: </strong>{{ .Alerts | len }}</h2>
          </div>
          <h3>Thông tin chi tiết cảnh báo:</h3>
          {{ range.Alerts }}
          <div class="alert {{ .Labels.severity }}">
            <h2>{{ .Labels.alertname }}</h2>
            <p><strong>Mức độ: </strong>{{ .Labels.severity }}</p>
            <p><strong>Tên máy chủ: </strong>{{ .Labels.instance }}</p>
            <p><strong>Thông điệp: </strong>{{ .Annotations.summary }}</p>
            <p><strong>Giá trị hiện tại: </strong>{{ .Annotations.value }}</p>
            <p>
              <strong>Thời gian bắt đầu: </strong
              >{{ .StartsAt.Local.Format "01/02/2006 15:04:05 " }}
            </p>
            <p><strong> Mô tả chi tiết: </strong>{{ .Annotations.description }}</p>
          </div>
          {{ end }}

          <p>
            Chúng tôi đang theo dõi tình trạng này và sẽ tiếp tục giám sát các sự
            kiện liên quan. Vui lòng kiểm tra và xử lý cảnh báo này càng sớm càng
            tốt.
          </p>

          <div class="footer">
            <p>Trân trọng</p>
          </div>
        </div>
      </body>
    </html>

    {{ end }}

type: Opaque



# alertmanagers:
# - api_version: v2
#   http_config:
#     basic_auth:
#       password: some_pass
#       username: some_user
#   scheme: http
#   static_configs:
#   - alertmanager.thanos.io
#   timeout: 10s